### ISSUE TITLE
Issue with game speed, slowdowns and how can be solved.

### ISSUE THREAD

**Issue by M1sh2** [metal-crow/Dark-Souls-1-Overhaul#10]
Hello, the game slows down at 30 frames, can run faster but at a lower frame rate (15-20-25 fps as in ptde). A way to fix this, i think should be add overclocking to speed up through cheat engine, which makes in my case close to the original speed. Is it possible to add a game simulation check, and automatically bring the speed close to the original speed ? I do not know why this was not done by default, because there are no such problems with ptde.
My specs: notebook, amd a8-4500M 1.90 GHz, Radeon HD 7600M + 7640G, 6 gb ram.

**Comment by metal-crow** [comment]
I assume this is for DSR, right? Not PTDE? Currently the only release is for PTDE, although i'm actively working on a DSR release.
As for your problem, i actually had never thought of trying to fix it by speedhacking before. Have you tested this? I feel like if you speedhacked the game to get the correct physics simulation speed then you'd be playing the game in slow motion, which isn't really desirable. And a more in-depth fix to make the physics not framerate dependent is unfortunately out of the question. If QLOC couldn't do it even with the source code, i certainly can't.

**Comment by M1sh2** [comment]
> 
> 
> I assume this is for DSR, right? Not PTDE? Currently the only release is for PTDE, although i'm actively working on a DSR release.
> As for your problem, i actually had never thought of trying to fix it by speedhacking before. Have you tested this? I feel like if you speedhacked the game to get the correct physics simulation speed then you'd be playing the game in slow motion, which isn't really desirable. And a more in-depth fix to make the physics not framerate dependent is unfortunately out of the question. If QLOC couldn't do it even with the source code, i certainly can't.

yes, this is in DSR, yes, i am already tested , in singleplayer only. The speed is adjusted via speedhack. But in some locations it changes automatically. (since the CPU load is reduced)

**Comment by metal-crow** [comment]
I have to say, i don't quite understand how exactly this is working. You can't, in software, make a game run faster when it's bottleneck is how fast the CPU can run. There's no way to overclock like that. If you speedhack a game, you are just lying to it about the time.

Speedhacking to slow down tells the game time is moving slower than it really is, so the game doesn't bother rendering the next frame until later then it normally would have. The game looks like it's in slow motion because it's outputting visuals slower, but from the internal persective nothing has changed.

Speedhacking to speed up does the opposite, telling the game time is moving faster than it really is. So the game tries to pump out more frames in the same amount of time it normally would. If you have overhead to spare between frames, this works and it can increase your FPS since the game was just artificially stopping itself from using the extra overhead. If the game is already struggling to pump out the normal amount of frames, though, this shouldn't do anything since it literally can't make the previous frame targets so it can't make the new ones.
