### ISSUE TITLE
No guide on how to install it?

### ISSUE THREAD

**Issue by AdamCerutti** [metal-crow/Dark-Souls-1-Overhaul#14]
Sorry to bloat the issues section with this, but I couldn't find any help anywhere else.

I'm trying to run it on DSR, so I assume I just plop the files into the game directory, but it doesn't seem to be working when I launch the game.

I test it by loading in, and trying to roll out of a gesture. If I can't cancel the gesture, I know the mod isn't working.

The readme has no instructions. I'm at a loss, please help.

**Comment by metal-crow** [comment]
Ah, you're trying to install the DSR version, right (not the old old one for PTDE)? Yeah, rn it has no install instructions because, well, it's still in super alpha atm XD

But installing should be easy enough. You just take the zip from the release and put everything from in it into your folder where the exe is (so d3d11.dll should be next to DarkSoulsRemastered.exe). You can see if it's enabled by setting the `ExternalOutputWindow` to 1 in the ini. and when you run DSR a cmd window should open and spit out text.

Both of these will be fixed in the beta/actual release.

**Comment by metal-crow** [comment]
the gesture roll out only works when it's in overhaul mode, not legacy mode, which is why you don't have it. You can set the default mode in the ini, or press f5 to change it when the game is on (the latter will be an actual in-game ui thing in the future)

**Comment by AdamCerutti** [comment]
I see, thank you. While I'm here, is there a reason the omni-rolling feature was removed?

**Comment by metal-crow** [comment]
It didn't actually work, for 1. All it did was make you roll like you were unlocked, which meant you couldn't roll backwards. Effectively, you'd turn around then roll forwards. Which really made it not useful in terms of PvP.
If people really want it, i might bring it back in a ring form, but i dunno if that's desired.
