### ISSUE TITLE
Overlay not working.

### ISSUE THREAD

**Issue by Nahnahchi** [metal-crow/Dark-Souls-1-Overhaul#9]
I'm on DSR and I tried opening the console, but it didn't show up. None of the shortcut keys are working and the supposed overlay doesn't seem to be present at all.

Nothing appears to be wrong during startup as all fixes are applied just fine.

**Comment by metal-crow** [comment]
Oh, that's easy! It's because the official release currently is only for PTDE. The current master build here is being made for DSR, so if you wanted to use the [latest release](https://github.com/metal-crow/Dark-Souls-1-Overhaul/releases/tag/d28a557) feel free, but it's all very preliminary at the moment, still got a lot of work to do before it's ready for large scale testing.

If you do want to use the pre-release with DSR, the console doesn't work for that, but you can enable the "ExternalOutputWindow" option in the ini to see what is being printed.

**Comment by SeanPesce** [comment]
For further clarification, we only have an in-game console/overlay on DirectX 9 (so only the Prepare to Die Edition). A DirectX 11 console & overlay are possible, but not a part of any near-term plans (as far as I'm aware).

**Comment by Nahnahchi** [comment]
Oh I see.

If that's the case, is it possible to customize this build if I only wanted some select features enabled?

**Comment by metal-crow** [comment]
For the remaster? not easily at the moment. It's on my list of thing-to-do to make features hotswappable (not just enabled/disabled, but can be toggled at runtime), but i haven't gotten to that task yet. If you really wanted you can compile the source yourself with the features you want commented out, but other than that nothing, sorry. The remaster mod is still super unfinished :(

**Comment by Nahnahchi** [comment]
Alright, thanks for the response!
